# .github/workflows/release.yml:
name: Release

on:
  pull_request:
    # run when you make a pull request onto the following branches
    branches:
      - main
    types: [closed]
    inputs:
      bump:
        description: "bump type, major or minor or patch or empty string"
        default: ""
      dry_run:
        description: "dry run, true or false"
        default: "false"
      draft:
        description: "draft, true or false"
        default: "false"
      pre_release:
        description: "pre release, true or false"
        default: "false"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: MeilCli/bump-release-action@v1
        with:
          config_path: ".github/bump.yml"
          bump: ${{ github.event.inputs.bump }}
          dry_run: ${{ github.event.inputs.dry_run }}
          draft: ${{ github.event.inputs.draft }}
          pre_release: ${{ github.event.inputs.pre_release }}

  changelog:
    exclude:
      labels:
        - ignore-for-release
      authors:
        - octocat
    categories:
      - title: Breaking Changes 🛠
        labels:
          - Semver-Major
          - breaking-change
      - title: Exciting New Features 🎉
        labels:
          - Semver-Minor
          - enhancement
      - title: Other Changes
        labels:
          - "*"
